// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0rOzKvfIBYikuDXatJMUJPFMnqsnYI5E',
    appId: '1:482300625189:web:00eb0c10820eab97d51acc',
    messagingSenderId: '482300625189',
    projectId: 'firestoreday16-app',
    authDomain: 'firestoreday16-app.firebaseapp.com',
    storageBucket: 'firestoreday16-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqmJAm5QNMYAVb6Yshor55V61SVrSdt6o',
    appId: '1:482300625189:android:0f4461f89efcf3f9d51acc',
    messagingSenderId: '482300625189',
    projectId: 'firestoreday16-app',
    storageBucket: 'firestoreday16-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2zy0nlYp1fzJuGSEU3JkiscyX6p6FdGQ',
    appId: '1:482300625189:ios:3cb49bd79ee4f21dd51acc',
    messagingSenderId: '482300625189',
    projectId: 'firestoreday16-app',
    storageBucket: 'firestoreday16-app.firebasestorage.app',
    iosClientId: '482300625189-tvvn13m4ufi9oqufr8vsng0j75vt6ra2.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2zy0nlYp1fzJuGSEU3JkiscyX6p6FdGQ',
    appId: '1:482300625189:ios:3cb49bd79ee4f21dd51acc',
    messagingSenderId: '482300625189',
    projectId: 'firestoreday16-app',
    storageBucket: 'firestoreday16-app.firebasestorage.app',
    iosClientId: '482300625189-tvvn13m4ufi9oqufr8vsng0j75vt6ra2.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0rOzKvfIBYikuDXatJMUJPFMnqsnYI5E',
    appId: '1:482300625189:web:1ef7c336f05db083d51acc',
    messagingSenderId: '482300625189',
    projectId: 'firestoreday16-app',
    authDomain: 'firestoreday16-app.firebaseapp.com',
    storageBucket: 'firestoreday16-app.firebasestorage.app',
  );
}